# Generated by Django 3.0.8 on 2020-11-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.TextField()),
                ('organisation', models.TextField()),
                ('description', models.TextField()),
                ('objectives', models.TextField()),
                ('image', models.URLField(null=True)),
                ('duration', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('opp_type', models.TextField()),
                ('opp_link', models.URLField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
