# Generated by Django 3.0.8 on 2020-11-23 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_opportunity_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='duration',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='close_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_date',
            field=models.DateField(),
        ),
    ]
